### ISSUE TITLE
[STOP!] Page Numbers

### ISSUE THREAD

**Issue by XioNYC** [XioNYC/StarRaiders#18]
It's clear that there's a page numbering problem, probably stemming from [this](https://twitter.com/XioNYC/status/655630057143185408).  Please hold off until this problem is fixed.

**Comment by colorado5** [comment]
Also have a problem with page 72 - it's pg. 73 instead in Works in Progress folder. That's one tricky PDF file, I'm surprised no one else has worked on the wrong page before this.   New to github, I don't know how to 'create a file in this subdirectory' to post page 74 I have done or more I wanted to do.  Waiting for go ahead and how to for this noob.

Reviewed repeated page issue, saw it and I don't see a problem with it unless you are behind the curtains working the levers?

**Comment by mattcodez** [comment]
I did page 72, based on the url for the archive viewer.

**Comment by colorado5** [comment]
Hi, mattcodez, too new to understand what you meant exactly but in the PDF file I downloaded your page 72 is page 73.  If we skip the trouble spot of page 18 and the blank pages like 6 and 9, the PDF file matches all saved pages so far, except for your last work.  I didn't want to do 'the real' 72 since your file is already named that so I did 74 but don't know how or even if it's possible to submit it at this point in time.  The PDF has a single first page and then it switches to two pages side by side, very easy to wind up on the next page but the page number does show the transition correctly caused by going sideways without really noticing that this has happened so I have my eye on that number.  I'm using Adobe reader off line though maybe that makes a difference?

**Comment by rnelsonxmission** [comment]
There is a button in the PDF viewer to switch to single page mode, near the bottom right.  This eliminates the confusion.  Also zooming in close is helpful.

-rob

**Comment by mattcodez** [comment]
@colorado5 I see what you're saying now. Viewing in the Archive.org browser, the URL says n72, but in Acrobat reader, it is page 73.

@XioNYC Where has the page number been taken for previous pages?

**Comment by colorado5** [comment]
Not doing it that way to start with I can only suggest that maybe it's just luck that odd (even?) pages aren't so prone to this particular foible?  I'm zoomed in pretty good anyway and my glasses are way down on the end of my nose even then.  Don't get old people.

**Comment by deckar01** [comment]
The issue is that the archive's document viewer uses 0 based indexing for the URL.
It is clearer in the single page view that when you float over the slider handle the correct page number is displayed.

I mentioned issues with the page numbers in #16 and suggested providing an explicit link to each page.

I am looking into the archive's book reader repo to see if it causes the 0 based indexing issue.
https://github.com/internetarchive/bookreader
https://github.com/openlibrary/bookreader

**Comment by XioNYC** [comment]
Hey, all.  Sorry for dumping this problem on you/youse/y'all without following-up - I've been so sick the last few days that Atari DOS 3 seems a really keen idea....

I've been working from the TIFFs that Kevin uploaded and most everyone else has been working from the PDF version on Internet Archive.  Since I got the TIFFs before I discovered the duplicate page, my numbering is off-by-one (don'cha jus' hate it when that happens?).

What I'll do is go page-by-page from the PDF version and make a table of "official" page numbers and include the first address/line listed on the page.  I'll see if I can add in a column for who's doing a page.

**Comment by mattcodez** [comment]
Any update on this? Do you need any help with getting this table built?

**Comment by jeffpiep** [comment]
I wrote a Python script to extract the first and last address of each file ('nnn.txt') that's already been typed in. It's in the main directory of my fork. [Results are here](https://github.com/jeffpiep/StarRaiders/blob/master/addresses.txt), if it helps.

**Comment by XioNYC** [comment]
All pages accoutned for.  Resolved & closing.
