### ISSUE TITLE
002: Variable Name

### ISSUE THREAD

**Issue by XioNYC** [XioNYC/StarRaiders#4]
Line $0067 (second line?!) "PRGCST", "PRG0ST", "PROCST", or "PRO0ST"??

**Comment by jzatarski** [comment]
the third character is an 'O'. The bottom piece extends up too far to be 'C' and '0' is a rounder character, while 'O' is more square.
The fourth character is not a 'C', as the gap is too small. It's likely a 'G', not a '0', because of the way the top 'tail' is sloping rather than 'curving' like a '0'.
Additionally, the label 'PROGST' likely means program start, and makes sense as a label, whereas the other possibilities make less sense, without a meaningful comment to describe it.

**Comment by XioNYC** [comment]
Thanks!
